const puppeteer = require('puppeteer');
var arg = process.argv.splice(2);
async function kkkc(url) {
    const browser = await puppeteer.launch({
        headless: true // 开启界面
    });
    const cookies = [
        {
            "domain": ".pixiv.net",
            "expirationDate": 1692690281.61814,
            "hostOnly": false,
            "httpOnly": true,
            "name": "__cf_bm",
            "path": "/",
            "sameSite": "no_restriction",
            "secure": true,
            "session": false,
            "storeId": "0",
            "value": "TkgzkClaABdqpPGFH1ZNm6vUuSjNU2xTpsKCeJaMBWo-1692688481-0-Ae/3Orz2M/p3ByeE8xFJAq6b1SmIuh6Ky2U4qJ2l4FZOEsxknIBsMh8DbNrVdS1z9fh1fGVAIPTHCCfouh8VAVWAZGwr4l6CLpSxd0CSrTeS",
            "id": 1
        },
        {
            "domain": ".pixiv.net",
            "expirationDate": 1727248205.899867,
            "hostOnly": false,
            "httpOnly": false,
            "name": "__utma",
            "path": "/",
            "sameSite": "unspecified",
            "secure": false,
            "session": false,
            "storeId": "0",
            "value": "235335808.436314191.1691207414.1692678957.1692683690.3",
            "id": 2
        },
        {
            "domain": ".pixiv.net",
            "expirationDate": 1692690005,
            "hostOnly": false,
            "httpOnly": false,
            "name": "__utmb",
            "path": "/",
            "sameSite": "unspecified",
            "secure": false,
            "session": false,
            "storeId": "0",
            "value": "235335808.31.10.1692683690",
            "id": 3
        },
        {
            "domain": ".pixiv.net",
            "hostOnly": false,
            "httpOnly": false,
            "name": "__utmc",
            "path": "/",
            "sameSite": "unspecified",
            "secure": false,
            "session": true,
            "storeId": "0",
            "value": "235335808",
            "id": 4
        },
        {
            "domain": ".pixiv.net",
            "expirationDate": 1727248205.900004,
            "hostOnly": false,
            "httpOnly": false,
            "name": "__utmv",
            "path": "/",
            "sameSite": "unspecified",
            "secure": false,
            "session": false,
            "storeId": "0",
            "value": "235335808.|2=login%20ever=no=1^3=plan=normal=1^5=gender=male=1^6=user_id=49343042=1^9=p_ab_id=1=1^10=p_ab_id_2=4=1^11=lang=zh=1",
            "id": 5
        },
        {
            "domain": ".pixiv.net",
            "expirationDate": 1708456205,
            "hostOnly": false,
            "httpOnly": false,
            "name": "__utmz",
            "path": "/",
            "sameSite": "unspecified",
            "secure": false,
            "session": false,
            "storeId": "0",
            "value": "235335808.1691207414.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)",
            "id": 6
        },
        {
            "domain": ".pixiv.net",
            "expirationDate": 1698983419,
            "hostOnly": false,
            "httpOnly": false,
            "name": "_fbp",
            "path": "/",
            "sameSite": "lax",
            "secure": false,
            "session": false,
            "storeId": "0",
            "value": "fb.1.1691207418857.1491705339",
            "id": 7
        },
        {
            "domain": ".pixiv.net",
            "expirationDate": 1727248207.022191,
            "hostOnly": false,
            "httpOnly": false,
            "name": "_ga",
            "path": "/",
            "sameSite": "unspecified",
            "secure": false,
            "session": false,
            "storeId": "0",
            "value": "GA1.2.459216914.1691207414",
            "id": 8
        },
        {
            "domain": ".pixiv.net",
            "expirationDate": 1727248207.014913,
            "hostOnly": false,
            "httpOnly": false,
            "name": "_ga_75BBYNYN9J",
            "path": "/",
            "sameSite": "unspecified",
            "secure": false,
            "session": false,
            "storeId": "0",
            "value": "GS1.1.1692683692.4.1.1692688207.0.0.0",
            "id": 9
        },
        {
            "domain": ".pixiv.net",
            "expirationDate": 1727239123.727238,
            "hostOnly": false,
            "httpOnly": false,
            "name": "_ga_MZ1NL4PHH0",
            "path": "/",
            "sameSite": "unspecified",
            "secure": false,
            "session": false,
            "storeId": "0",
            "value": "GS1.1.1692679042.1.1.1692679123.0.0.0",
            "id": 10
        },
        {
            "domain": ".pixiv.net",
            "expirationDate": 1692774607,
            "hostOnly": false,
            "httpOnly": false,
            "name": "_gid",
            "path": "/",
            "sameSite": "unspecified",
            "secure": false,
            "session": false,
            "storeId": "0",
            "value": "GA1.2.1859355025.1692679138",
            "id": 11
        },
        {
            "domain": ".pixiv.net",
            "expirationDate": 1727248091.280178,
            "hostOnly": false,
            "httpOnly": false,
            "name": "a_type",
            "path": "/",
            "sameSite": "unspecified",
            "secure": true,
            "session": false,
            "storeId": "0",
            "value": "0",
            "id": 12
        },
        {
            "domain": ".pixiv.net",
            "expirationDate": 1727248091.280186,
            "hostOnly": false,
            "httpOnly": false,
            "name": "b_type",
            "path": "/",
            "sameSite": "unspecified",
            "secure": true,
            "session": false,
            "storeId": "0",
            "value": "1",
            "id": 13
        },
        {
            "domain": ".pixiv.net",
            "expirationDate": 1727248091.280113,
            "hostOnly": false,
            "httpOnly": false,
            "name": "c_type",
            "path": "/",
            "sameSite": "unspecified",
            "secure": true,
            "session": false,
            "storeId": "0",
            "value": "26",
            "id": 14
        },
        {
            "domain": ".pixiv.net",
            "expirationDate": 1724224059.306354,
            "hostOnly": false,
            "httpOnly": true,
            "name": "cf_clearance",
            "path": "/",
            "sameSite": "no_restriction",
            "secure": true,
            "session": false,
            "storeId": "0",
            "value": "wkga56cprxfwxk.9y1FY74CWhSy7M0jfFUhk2rYKGms-1692688058-0-1-fc1bb2d3.3d986202.ab1aed33-0.2.1692688058",
            "id": 15
        },
        {
            "domain": ".pixiv.net",
            "expirationDate": 1695271115.283621,
            "hostOnly": false,
            "httpOnly": true,
            "name": "device_token",
            "path": "/",
            "sameSite": "unspecified",
            "secure": true,
            "session": false,
            "storeId": "0",
            "value": "40fda467a69354363f4e35f69dac6c46",
            "id": 16
        },
        {
            "domain": ".pixiv.net",
            "expirationDate": 1725767407.291047,
            "hostOnly": false,
            "httpOnly": false,
            "name": "p_ab_d_id",
            "path": "/",
            "sameSite": "unspecified",
            "secure": true,
            "session": false,
            "storeId": "0",
            "value": "62976449",
            "id": 17
        },
        {
            "domain": ".pixiv.net",
            "expirationDate": 1725767407.291035,
            "hostOnly": false,
            "httpOnly": false,
            "name": "p_ab_id",
            "path": "/",
            "sameSite": "unspecified",
            "secure": true,
            "session": false,
            "storeId": "0",
            "value": "1",
            "id": 18
        },
        {
            "domain": ".pixiv.net",
            "expirationDate": 1725767407.291041,
            "hostOnly": false,
            "httpOnly": false,
            "name": "p_ab_id_2",
            "path": "/",
            "sameSite": "unspecified",
            "secure": true,
            "session": false,
            "storeId": "0",
            "value": "4",
            "id": 19
        },
        {
            "domain": ".pixiv.net",
            "expirationDate": 1695280091.280157,
            "hostOnly": false,
            "httpOnly": true,
            "name": "PHPSESSID",
            "path": "/",
            "sameSite": "unspecified",
            "secure": true,
            "session": false,
            "storeId": "0",
            "value": "49343042_j0WRJL8M6Ta1RyZpcsMRCkyqWcQ2XxWH",
            "id": 20
        },
        {
            "domain": ".pixiv.net",
            "expirationDate": 1727239137.099408,
            "hostOnly": false,
            "httpOnly": true,
            "name": "privacy_policy_agreement",
            "path": "/",
            "sameSite": "unspecified",
            "secure": true,
            "session": false,
            "storeId": "0",
            "value": "6",
            "id": 21
        },
        {
            "domain": ".pixiv.net",
            "expirationDate": 1727248091.280168,
            "hostOnly": false,
            "httpOnly": true,
            "name": "privacy_policy_notification",
            "path": "/",
            "sameSite": "unspecified",
            "secure": true,
            "session": false,
            "storeId": "0",
            "value": "0",
            "id": 22
        },
        {
            "domain": "www.pixiv.net",
            "expirationDate": 1725767407.290997,
            "hostOnly": true,
            "httpOnly": false,
            "name": "first_visit_datetime_pc",
            "path": "/",
            "sameSite": "unspecified",
            "secure": true,
            "session": false,
            "storeId": "0",
            "value": "2023-08-05+12%3A50%3A06",
            "id": 23
        },
        {
            "domain": "www.pixiv.net",
            "expirationDate": 1693283957,
            "hostOnly": true,
            "httpOnly": false,
            "name": "QSI_S_ZN_5hF4My7Ad6VNNAi",
            "path": "/",
            "sameSite": "unspecified",
            "secure": false,
            "session": false,
            "storeId": "0",
            "value": "v:0:0",
            "id": 24
        },
        {
            "domain": "www.pixiv.net",
            "expirationDate": 1725767407.291052,
            "hostOnly": true,
            "httpOnly": false,
            "name": "yuid_b",
            "path": "/",
            "sameSite": "unspecified",
            "secure": true,
            "session": false,
            "storeId": "0",
            "value": "UTeIAhA",
            "id": 25
        }
    ]
    const page = await browser.newPage(); // 新建页面
    await page.goto(url, {
        waitUntil: 'networkidle2'
    });
    await page.setCookie(...cookies);
    await page.reload();
    const ele = await page.$eval('pre', el => el.textContent);
    console.log(ele);
    await browser.close();
}
kkkc(arg[0])