const puppeteer = require('puppeteer');
var arg = process.argv.splice(2);
async function kkkc(url) {
    const browser = await puppeteer.launch({
        headless: true // 开启界面
    });
    const cookies = [
{
    "domain": ".pixiv.net",
    "expirationDate": 1663570212,
    "hostOnly": false,
    "httpOnly": false,
    "name": "__utma",
    "path": "/",
    "sameSite": "unspecified",
    "secure": false,
    "session": false,
    "storeId": "0",
    "value": "235335808.1294526804.1600175901.1600497761.1600498137.19",
    "id": 1
},
{
    "domain": ".pixiv.net",
    "expirationDate": 1600500012,
    "hostOnly": false,
    "httpOnly": false,
    "name": "__utmb",
    "path": "/",
    "sameSite": "unspecified",
    "secure": false,
    "session": false,
    "storeId": "0",
    "value": "235335808.2.10.1600498137",
    "id": 2
},
{
    "domain": ".pixiv.net",
    "hostOnly": false,
    "httpOnly": false,
    "name": "__utmc",
    "path": "/",
    "sameSite": "unspecified",
    "secure": false,
    "session": true,
    "storeId": "0",
    "value": "235335808",
    "id": 3
},
{
    "domain": ".pixiv.net",
    "expirationDate": 1600498361,
    "hostOnly": false,
    "httpOnly": false,
    "name": "__utmt",
    "path": "/",
    "sameSite": "unspecified",
    "secure": false,
    "session": false,
    "storeId": "0",
    "value": "1",
    "id": 4
},
{
    "domain": ".pixiv.net",
    "expirationDate": 1663570212,
    "hostOnly": false,
    "httpOnly": false,
    "name": "__utmv",
    "path": "/",
    "sameSite": "unspecified",
    "secure": false,
    "session": false,
    "storeId": "0",
    "value": "235335808.|2=login%20ever=yes=1^3=plan=normal=1^5=gender=male=1^6=user_id=54167627=1^9=p_ab_id=6=1^10=p_ab_id_2=2=1^11=lang=zh=1",
    "id": 5
},
{
    "domain": ".pixiv.net",
    "expirationDate": 1616266212,
    "hostOnly": false,
    "httpOnly": false,
    "name": "__utmz",
    "path": "/",
    "sameSite": "unspecified",
    "secure": false,
    "session": false,
    "storeId": "0",
    "value": "235335808.1600498137.19.2.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=(not%20provided)",
    "id": 6
},
{
    "domain": ".pixiv.net",
    "expirationDate": 1608274213,
    "hostOnly": false,
    "httpOnly": false,
    "name": "_fbp",
    "path": "/",
    "sameSite": "lax",
    "secure": false,
    "session": false,
    "storeId": "0",
    "value": "fb.1.1600175901889.1381699109",
    "id": 7
},
{
    "domain": ".pixiv.net",
    "expirationDate": 1663570005,
    "hostOnly": false,
    "httpOnly": false,
    "name": "_ga",
    "path": "/",
    "sameSite": "unspecified",
    "secure": false,
    "session": false,
    "storeId": "0",
    "value": "GA1.2.1294526804.1600175901",
    "id": 8
},
{
    "domain": ".pixiv.net",
    "expirationDate": 1600584405,
    "hostOnly": false,
    "httpOnly": false,
    "name": "_gid",
    "path": "/",
    "sameSite": "unspecified",
    "secure": false,
    "session": false,
    "storeId": "0",
    "value": "GA1.2.324411859.1600214533",
    "id": 9
},
{
    "domain": ".pixiv.net",
    "expirationDate": 1663570136.776779,
    "hostOnly": false,
    "httpOnly": false,
    "name": "a_type",
    "path": "/",
    "sameSite": "unspecified",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "0",
    "id": 10
},
{
    "domain": ".pixiv.net",
    "expirationDate": 1663570136.776808,
    "hostOnly": false,
    "httpOnly": false,
    "name": "b_type",
    "path": "/",
    "sameSite": "unspecified",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "0",
    "id": 11
},
{
    "domain": ".pixiv.net",
    "expirationDate": 1663570136.776679,
    "hostOnly": false,
    "httpOnly": false,
    "name": "c_type",
    "path": "/",
    "sameSite": "unspecified",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "23",
    "id": 12
},
{
    "domain": ".pixiv.net",
    "expirationDate": 1603090000.298207,
    "hostOnly": false,
    "httpOnly": true,
    "name": "device_token",
    "path": "/",
    "sameSite": "unspecified",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "6771f0047f0206ac76b0d887ad6f8154",
    "id": 13
},
{
    "domain": ".pixiv.net",
    "expirationDate": 1757855897.246798,
    "hostOnly": false,
    "httpOnly": false,
    "name": "p_ab_d_id",
    "path": "/",
    "sameSite": "unspecified",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "1548350158",
    "id": 14
},
{
    "domain": ".pixiv.net",
    "expirationDate": 1757855897.246764,
    "hostOnly": false,
    "httpOnly": false,
    "name": "p_ab_id",
    "path": "/",
    "sameSite": "unspecified",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "6",
    "id": 15
},
{
    "domain": ".pixiv.net",
    "expirationDate": 1757855897.246781,
    "hostOnly": false,
    "httpOnly": false,
    "name": "p_ab_id_2",
    "path": "/",
    "sameSite": "unspecified",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "2",
    "id": 16
},
{
    "domain": ".pixiv.net",
    "expirationDate": 1600856993.267642,
    "hostOnly": false,
    "httpOnly": true,
    "name": "p_b_type",
    "path": "/",
    "sameSite": "unspecified",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "2",
    "id": 17
},
{
    "domain": ".pixiv.net",
    "expirationDate": 1603090136.776745,
    "hostOnly": false,
    "httpOnly": true,
    "name": "PHPSESSID",
    "path": "/",
    "sameSite": "unspecified",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "54167627_vgNLoMtwbkByNqG382ZHOSbzgfGkboVF",
    "id": 18
},
{
    "domain": ".pixiv.net",
    "expirationDate": 1663570000.521868,
    "hostOnly": false,
    "httpOnly": true,
    "name": "privacy_policy_agreement",
    "path": "/",
    "sameSite": "unspecified",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "2",
    "id": 19
},
{
    "domain": ".pixiv.net",
    "expirationDate": 1663554841.507351,
    "hostOnly": false,
    "httpOnly": false,
    "name": "tag_view_ranking",
    "path": "/",
    "sameSite": "unspecified",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "Lt-oEicbBr~eVxus64GZU~ahqc2_Z8SY~RTJMXD26Ak~7dr5yDiiNE~yvN_bfBdr-~afkK5n8h7Y~fLVJtGGhWk~0-sOOtqkAh~6RcLf9BQ-w~NxCKECN-a3~5uR0C2H1G-~88CzNsCQ-T~sr5scJlaNv~O2wfZxfonb~PHQDP-ccQD~02XYWZUIFd~MSNRmMUDgC~kGYw4gQ11Z~0xsDLqCEW6~A7hSoqw-5Z~ETjPkL0e6r~HY55MqmzzQ~OGMdJys38W~k3AcsamkCa~nBTsmJOROI~1HuE7w0nKg~ePN3h1AXKX~4ZJCd8OsPC~fIMPtFR8GH~RcahSSzeRf~CrFcrMFJzz~pYlUxeIoeg~K8esoIs2eW~dkvvzKpAOm~FqVQndhufZ~MHugbgF9Xo~FFz0M9z5uL~kUbnfdh8c_~TPdzb_n7qh~p1FQfxQRtJ~70wHD0F49f~eNdHeRUOQ3~OIoyEaauWk~vNapp9tuHK~2z4S7nphJy~tAvX8S-RSe~l-Y6C2rjLn~4DWYEq_Arj~CAJC_jOheS~BQFWWhxtER~jH0uD88V6F~F5CBR92p_Q~Mt5-5Xt_R_~X189mzByda~-zk8AVVQ-j~yLh4ENOaur~9PHNivVcYr~8_wOYu6BZ5~HLWLeyYOUF~lH5YZxnbfC~tMaqyr0fI5~VN7cgWyMmg~wKl4cqK7Gl~dFqfRYFNxQ~BU9SQkS-zU~hrkSAnsIgX~y8GNntYHsi~2h8ZfJVouI",
    "id": 20
},
{
    "domain": ".www.pixiv.net",
    "expirationDate": 1602767896.246668,
    "hostOnly": false,
    "httpOnly": true,
    "name": "__cfduid",
    "path": "/",
    "sameSite": "lax",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "d577fc02e8bfc3b7a913dffa292912e521600175914",
    "id": 21
},
{
    "domain": ".www.pixiv.net",
    "expirationDate": 1757939841,
    "hostOnly": false,
    "httpOnly": false,
    "name": "login_ever",
    "path": "/",
    "sameSite": "unspecified",
    "secure": false,
    "session": false,
    "storeId": "0",
    "value": "yes",
    "id": 22
},
{
    "domain": "www.pixiv.net",
    "expirationDate": 1603089769,
    "hostOnly": true,
    "httpOnly": false,
    "name": "categorized_tags",
    "path": "/",
    "sameSite": "unspecified",
    "secure": false,
    "session": false,
    "storeId": "0",
    "value": "6sZKldb07K~BU9SQkS-zU~DN6RDM1CuJ~EGefOqA6KB~IVwLyT8B6k~Mt5-5Xt_R_~NqnXOnazer~O2wfZxfonb~OEXgaiEbRa~OT-C6ubi9i~PHQDP-ccQD~RcahSSzeRf~b8b4-hqot7~sr5scJlaNv~tMaqyr0fI5~y8GNntYHsi",
    "id": 23
},
{
    "domain": "www.pixiv.net",
    "expirationDate": 1663247897.246721,
    "hostOnly": true,
    "httpOnly": false,
    "name": "first_visit_datetime_pc",
    "path": "/",
    "sameSite": "unspecified",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "2020-09-15+22%3A18%3A35",
    "id": 24
},
{
    "domain": "www.pixiv.net",
    "expirationDate": 1758244133,
    "hostOnly": true,
    "httpOnly": false,
    "name": "ki_r",
    "path": "/",
    "sameSite": "unspecified",
    "secure": false,
    "session": false,
    "storeId": "0",
    "value": "",
    "id": 25
},
{
    "domain": "www.pixiv.net",
    "expirationDate": 1758104604,
    "hostOnly": true,
    "httpOnly": false,
    "name": "ki_s",
    "path": "/",
    "sameSite": "unspecified",
    "secure": false,
    "session": false,
    "storeId": "0",
    "value": "210251%3A0.0.0.0.2",
    "id": 26
},
{
    "domain": "www.pixiv.net",
    "expirationDate": 1758244133,
    "hostOnly": true,
    "httpOnly": false,
    "name": "ki_t",
    "path": "/",
    "sameSite": "unspecified",
    "secure": false,
    "session": false,
    "storeId": "0",
    "value": "1600214550602%3B1600477733055%3B1600477733055%3B5%3B54",
    "id": 27
},
{
    "domain": "www.pixiv.net",
    "expirationDate": 1605661747,
    "hostOnly": true,
    "httpOnly": false,
    "name": "limited_ads",
    "path": "/users",
    "sameSite": "unspecified",
    "secure": false,
    "session": false,
    "storeId": "0",
    "value": "%7B%22responsive%22%3A%22%22%7D",
    "id": 28
},
{
    "domain": "www.pixiv.net",
    "expirationDate": 1605599740,
    "hostOnly": true,
    "httpOnly": false,
    "name": "limited_ads",
    "path": "/",
    "sameSite": "unspecified",
    "secure": false,
    "session": false,
    "storeId": "0",
    "value": "%7B%22responsive%22%3A%22%22%7D",
    "id": 29
},
{
    "domain": "www.pixiv.net",
    "expirationDate": 1600504969,
    "hostOnly": true,
    "httpOnly": false,
    "name": "tags_sended",
    "path": "/",
    "sameSite": "unspecified",
    "secure": false,
    "session": false,
    "storeId": "0",
    "value": "1",
    "id": 30
},
{
    "domain": "www.pixiv.net",
    "expirationDate": 1663247897.246813,
    "hostOnly": true,
    "httpOnly": false,
    "name": "yuid_b",
    "path": "/",
    "sameSite": "unspecified",
    "secure": true,
    "session": false,
    "storeId": "0",
    "value": "NJkxZUA",
    "id": 31
}
]
    const page = await browser.newPage(); // 新建页面
    await page.goto(url, {
        waitUntil: 'networkidle2'
    });
    await page.setCookie(...cookies);
    await page.reload();
    const ele = await page.$eval('pre', el => el.textContent);
    console.log(ele);
    await browser.close();
}
kkkc(arg[0])